/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_pnas_demo_ui_shadow_jni_JniUtils */

#ifndef _Included_com_pnas_demo_ui_shadow_jni_JniUtils
#define _Included_com_pnas_demo_ui_shadow_jni_JniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pnas_demo_ui_shadow_jni_JniUtils
 * Method:    get
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_pnas_demo_ui_shadow_jni_JniUtils_get
  (JNIEnv *, jclass);

/*
 * Class:     com_pnas_demo_ui_shadow_jni_JniUtils
 * Method:    set
 * Signature: (Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_pnas_demo_ui_shadow_jni_JniUtils_set
  (JNIEnv *, jclass, jstring);

#ifdef __cplusplus
}
#endif
#endif
